services:
  rpi-builder:
    build: .
    platform: linux/arm/v6
    working_dir: /home
    volumes:
      - ../../:/home
    command: >
      sh -c "cmake . -DCMAKE_CXX_STANDARD=14 -Dprotobuf_BUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=$(pwd)/output &&
             cmake --build . --parallel 4 &&
             ctest &&
             cmake --install ."
